# Generated by Django 3.0.5 on 2020-04-20 15:58

import api.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200408_0257'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageLog',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('encrypted_image_base64', api.utils.Base64Field(
                    db_column='encrypted_image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='api.Victim')),
            ],
        ),
    ]
