# Generated by Django 3.0.5 on 2020-04-08 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200408_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='victim',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='victim',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
