# Generated by Django 3.0.5 on 2020-04-25 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_logrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagelog',
            name='image',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='imagelog',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='log',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='log',
            name='title',
            field=models.TextField(),
        ),
    ]
