# Generated by Django 3.0.5 on 2020-04-27 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_log_is_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageLog',
        ),
    ]
