# Generated by Django 3.0.5 on 2020-04-27 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_delete_imagelog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
