# Generated by Django 3.0.5 on 2020-04-27 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_delete_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='victim',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='victim',
            name='password',
        ),
    ]
