server:
  port: 5000

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://aad04625r5lt2s.cf8wk2uwxdv0.us-west-2.rds.amazonaws.com:3306/epsipv?useSSL=false&useUnicode=yes&characterEncoding=UTF-8
    username: admin
    password: epsipv111
  session:
    store-type: jdbc
    jdbc:
      table-name: SPRING_SESSION
      initialize-schema: always
  app:
    jwtSecret: JWTSuperSecretKey
    jwtExpirationInMs: 604800000


mybatis:
  mapper-locations: mappers/*