// Authentication related actions
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_TYPE_SELECT_SUCCESS = 'USER_TYPE_SELECT_SUCCESS';
export const USER_TYPE_RESET_SUCCESS = 'USER_TYPE_RESET_SUCCESS';
export const FIRST_LOGIN = 'FIRST_LOGIN';
export const PRIVATE_KEY_DOWNLOADED = 'PRIVATE_KEY_DOWNLOADED';

// Educational post related actions
export const ADD_NEW_POST_LOADING = 'ADD_NEW_POST_LOADING';
export const ADD_NEW_POST_SUCCESS = 'ADD_NEW_POST_SUCCESS';
export const ADD_NEW_POST_FAIL = 'ADD_NEW_POST_FAIL';
export const FETCH_POSTS_LOADING = 'FETCH_POSTS_LOADING';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_FAIL = 'FETCH_POSTS_FAIL';
export const FETCH_SINGLE_POST_LOADING = 'FETCH_SINGLE_POST_LOADING';
export const FETCH_SINGLE_POST_SUCCESS = 'FETCH_SINGLE_POST_SUCCESS';
export const FETCH_SINGLE_POST_FAIL = 'FETCH_SINGLE_POST_FAIL';

// Error related actions
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
