// Authentication related actions
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_TYPE_SELECT_SUCCESS = 'USER_TYPE_SELECT_SUCCESS';
export const USER_TYPE_RESET_SUCCESS = 'USER_TYPE_RESET_SUCCESS';
export const FIRST_LOGIN = 'FIRST_LOGIN';
export const PRIVATE_KEY_DOWNLOADED = 'PRIVATE_KEY_DOWNLOADED';
export const OPT_OUT_LOG = 'OPT_OUT_LOG';

// Educational post related actions
export const ADD_NEW_POST_LOADING = 'ADD_NEW_POST_LOADING';
export const ADD_NEW_POST_SUCCESS = 'ADD_NEW_POST_SUCCESS';
export const ADD_NEW_POST_FAIL = 'ADD_NEW_POST_FAIL';
export const FETCH_POSTS_LOADING = 'FETCH_POSTS_LOADING';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_FAIL = 'FETCH_POSTS_FAIL';
export const FETCH_SINGLE_POST_LOADING = 'FETCH_SINGLE_POST_LOADING';
export const FETCH_SINGLE_POST_SUCCESS = 'FETCH_SINGLE_POST_SUCCESS';
export const FETCH_SINGLE_POST_FAIL = 'FETCH_SINGLE_POST_FAIL';

// Log actions
export const ADD_NEW_LOG_SUCCESS = 'ADD_NEW_LOG_SUCCESS';
export const ADD_NEW_LOG_FAIL = 'ADD_NEW_LOG_FAIL';
export const REQUEST_RETRIEVE_LOG_SUCCESS = 'REQUEST_RETRIEVE_LOG_SUCCESS';
export const REQUEST_RETRIEVE_LOG_FAIL = 'REQUEST_RETRIEVE_LOG_FAIL';
export const RETRIEVE_ALL_PROCCESSING_REQUESTS_SUCCESS =
  'RETRIEVE_ALL_PROCESSING_REQUESTS_SUCCESS';
export const RETRIEVE_ALL_PROCCESSING_REQUESTS_FAIL =
  'RETRIEVE_ALL_PROCESSING_REQUESTS_FAIL';
export const FETCH_SUBMITTED_LOGS_SUCCESS = 'FETCH_SUBMITTED_LOGS_SUCCESS';
export const FETCH_SUBMITTED_LOGS_FAIL = 'FETCH_SUBMITTED_LOGS_FAIL';

// Error related actions
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

// Success actions
export const GET_SUCCESS = 'GET_SUCCESS';
export const CLEAR_SUCCESS = 'CLEAR_SUCCESS';
